---
- hosts: webserver
  become: true
  become_method: sudo
  tasks:
    - name: Install the latest nginx
      apt: name=nginx state=latest

    - name: Start nginx
      service:
        name: nginx
        state: started

- hosts: appserver
  become: true
  become_method: sudo
  tasks:
    - name: Install nodejs and essentials
      apt:
        name: ['build-essential', 'nodejs']
        state: present
        update_cache: yes
